package(default_visibility = ["//visibility:public"])
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")
swift_library(
    name = "a_lib",
    srcs = [
        "A.swift",
    ],
    data = ["bazel-swift.png"],
)